# Generated by Django 4.1.2 on 2022-11-10 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinRecognitionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.PositiveIntegerField(verbose_name='Bin Number')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 14, 30, 20, 640640), verbose_name='Date of last request')),
                ('bank_name', models.CharField(max_length=250, verbose_name='Bank name')),
            ],
            options={
                'verbose_name': 'Known Bin number',
                'verbose_name_plural': 'Known Bin numbers',
            },
        ),
    ]
